### ISSUE TITLE
Please delete yourself

### ISSUE THREAD

**Issue by Lima-X-Coding** [MiroslavRD/MiroMEMZ#3]
You're a straight up Copycat, claiming that you build this yourself.

> Trojan that i made for myself

The only thing you did was to change some strings.

When you look into the code you can immediately see that nothing has been modified/changed (except the strings).
(So you'll probably don't have any knowledge about C/C++ and ASM)
The fact that you have 72 repositories which are all empty (except the forked ones) just shows you're a liar.

**Comment by MiroslavRD** [comment]
Go kill yourself, I'm gonna dox you later.
